# configserver > applicaton.yaml
server:
  port: 8889    # 컨피그 서버가 수신 대기하는 포트
#management:
    #endpoints:
    #endpoint:
     #   shutdown:
      #      enabled: true
       # web:
        #    exposure:
         #       include: "*"
spring:
    cloud:
        config:
            server:
                bootstrap: true

# logging 설정

logging:
  level:
    '[org.springframework.web]': debug
